<?php
$settings[] = array(
	'id'          => $the_prefix.'title',
	'label'       => __('Title', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'title'),
	'type'        => 'text',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'des',
	'label'       => __('Description', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'des'),
	'type'        => 'textarea',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'align',
	'label'       => __('Text Align', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'align'),
	'type'        => 'select',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => array( 
		array('value' => 'left','label' => 'left','src' => ''),
		array('value' => 'right','label' => 'right','src' => ''),
		array('value' => 'center','label' => 'center','src' => '')
	),
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'email',
	'label'       => __('Email', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'email'),
	'type'        => 'text',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'phone',
	'label'       => __('Phone', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'phone'),
	'type'        => 'text',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'address',
	'label'       => __('Address', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'address'),
	'type'        => 'textarea-simple',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);

$settings[] = array(
	'id'          => $the_prefix.'text_color',
	'label'       => __('Text Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'text_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'border_color',
	'label'       => __('Border Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'border_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'icon_color',
	'label'       => __('Icon Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'icon_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'icon_bg',
	'label'       => __('Icon Background Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'icon_bg'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'icon_border_color',
	'label'       => __('Icon Border Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'icon_border_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);