<?php
$home_slideshow_prefix = 'home_slideshow_';
$custom_settings['settings'][] = array(
	'id'          => 'home_tab_slideshow',
	'label'       => __('Slideshow', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => '',
	'type'        => 'tab',
	'section'     => 'home',
	'rows'        => '',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
);
$custom_settings['settings'][] = array(
	'id'          => $home_slideshow_prefix.'enable',
	'label'       => __('EnableSlideshow', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_option_std($home_slideshow_prefix.'enable'),
	'type'        => 'on_off',
	'section'     => 'home',
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
);

$custom_settings['settings'][] = array(
	'id'          => $home_slideshow_prefix.'description',
	'label'       => __('Section Description', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_option_std($home_slideshow_prefix.'description'),
	'type'        => 'textarea',
	'section'     => 'home',
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $home_slideshow_prefix.'enable:is(on)',
);
$custom_settings['settings'][] = array(
	'id'          => $home_slideshow_prefix.'items',
	'label'       => __('Slider Items', 'tally_taxdomain'),
	'desc'        => __('Add or edit info slider items.', 'tally_taxdomain'),
	'std'         => tally_option_std($home_slideshow_prefix.'items'),
	'type'        => 'list-item',
	'section'     => 'home',
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $home_slideshow_prefix.'enable:is(on)',
	'settings'    => array(
		array(
			'id'          => 'des',
			'label'       => __('Description', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'textarea-simple',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'image',
			'label'       => __('Image', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'upload',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'text_align',
			'label'       => __('Text Align', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'select',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'choices'     => array( 
				array('value' => 'left','label' => 'left','src' => ''),
				array('value' => 'right','label' => 'right','src' => ''),
				array('value' => 'center','label' => 'center','src' => '')
			),
		),
		array(
			'id'          => 'link',
			'label'       => __('Link', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'text',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'button_text',
			'label'       => __('Button Text', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'text',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'text_color',
			'label'       => __('Text Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'heading_color',
			'label'       => __('Heading Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'button_color',
			'label'       => __('Button Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		
	)
);
$custom_settings['settings'][] = array(
	'id'          => $home_slideshow_prefix.'image_size',
	'label'       => __('Image Size', 'tally_taxdomain'),
	'desc'        => __('Example: <strong>200x200</strong>', 'tally_taxdomain'),
	'std'         => tally_option_std($home_slideshow_prefix.'image_size'),
	'type'        => 'text',
	'section'     => 'home',
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $home_slideshow_prefix.'enable:is(on)',
);


$custom_settings['settings'][] = array(
	'id'          => $home_slideshow_prefix.'height',
	'label'       => __('Slider Height', 'tally_taxdomain'),
	'desc'        => __('Heaight of the slideshow. Example <strong>400</strong>', 'tally_taxdomain'),
	'std'         => tally_option_std($home_slideshow_prefix.'height'),
	'type'        => 'text',
	'section'     => 'home',
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $home_slideshow_prefix.'enable:is(on)',
);
$custom_settings['settings'][] = array(
	'id'          => $home_slideshow_prefix.'content_width',
	'label'       => __('Slideshow Content Width', 'tally_taxdomain'),
	'desc'        => __('Content width of the slideshow, example <strong>960</strong>', 'tally_taxdomain'),
	'std'         => tally_option_std($home_slideshow_prefix.'content_width'),
	'type'        => 'text',
	'section'     => 'home',
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $home_slideshow_prefix.'enable:is(on)',
);
$custom_settings['settings'][] = array(
	'id'          => $home_slideshow_prefix.'control_nav',
	'label'       => __('Control Nave', 'tally_taxdomain'),
	'desc'        => __('Enable or disable control navigation of the slideshow.', 'tally_taxdomain'),
	'std'         => tally_option_std($home_slideshow_prefix.'control_nav'),
	'type'        => 'on_off',
	'section'     => 'home',
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $home_slideshow_prefix.'enable:is(on)',
);
$custom_settings['settings'][] = array(
	'id'          => $home_slideshow_prefix.'direction_nav',
	'label'       => __('Direction Nav', 'tally_taxdomain'),
	'desc'        => __('Enable or disable Direction navigation of the slideshow.', 'tally_taxdomain'),
	'std'         => tally_option_std($home_slideshow_prefix.'direction_nav'),
	'type'        => 'on_off',
	'section'     => 'home',
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $home_slideshow_prefix.'enable:is(on)',
);