<?php
$settings[] = array(
	'id'          => $the_prefix.'title',
	'label'       => __('Title', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'title'),
	'type'        => 'text',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'content',
	'label'       => __('Content', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'content'),
	'type'        => 'textarea',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'align',
	'label'       => __('Text Align', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'align'),
	'type'        => 'select',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => array( 
		array('value' => 'left','label' => 'left','src' => ''),
		array('value' => 'right','label' => 'right','src' => ''),
		array('value' => 'center','label' => 'center','src' => '')
	),
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'buttons',
	'label'       => __('Buttons', 'tally_taxdomain'),
	'desc'        => __('Add or edit buttons.', 'tally_taxdomain'),
	'std'         => tally_hp_option_std($the_prefix .'buttons'),
	'type'        => 'list-item',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
	'settings'    => array(
		array(
			'id'          => 'link',
			'label'       => __('Link', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'text',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'color',
			'label'       => __('Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'select',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => 'tally-dis',
			'choices'     => '',
			'choices'     => array( 
				array('value' => 'accent','label' => 'accent','src' => ''),
				array('value' => 'light','label' => 'light','src' => ''),
				array('value' => 'dark','label' => 'dark','src' => '')
			),
		),
		array(
			'id'          => 'target',
			'label'       => __('Link Target', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'select',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => 'tally-dis',
			'choices'     => '',
			'choices'     => array( 
				array('value' => '_self','label' => '_self','src' => ''),
				array('value' => '_blank','label' => '_blank','src' => ''),
			),
		),
		array(
			'id'          => 'class',
			'label'       => __('Class', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'text',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => 'tally-dis',
			'choices'     => '',
		),
		
	)
);
$settings[] = array(
	'id'          => $the_prefix.'heading_color',
	'label'       => __('Heading Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'heading_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'text_color',
	'label'       => __('Text Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'text_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'border_color',
	'label'       => __('Border Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'border_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => 'tally-dis',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);