<?php
$settings[] = array(
	'id'          => $the_prefix.'items',
	'label'       => __('Content Items', 'tally_taxdomain'),
	'desc'        => __('Add or edit info Content items.', 'tally_taxdomain'),
	'std'         => tally_hp_option_std($the_prefix .'items'),
	'type'        => 'list-item',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
	'settings'    => array(
		array(
			'id'          => 'des',
			'label'       => __('Description', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'textarea-simple',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'image',
			'label'       => __('Image', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'upload',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'link',
			'label'       => __('Link', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'text',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'link_text',
			'label'       => __('Readmore Text', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'text',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'class',
			'label'       => __('Class', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'text',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'enable_color',
			'label'       => __('Enablse Color Options', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => 'off',
			'type'        => 'on-off',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
		),
		array(
			'id'          => 'heading_color',
			'label'       => __('Heading Text Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'condition'   => 'enable_color:is(on)',
			'operator'    => 'and',
		),
		array(
			'id'          => 'text_color',
			'label'       => __('Text Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'condition'   => 'enable_color:is(on)',
			'operator'    => 'and',
		),
		array(
			'id'          => 'border_color',
			'label'       => __('Border Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'condition'   => 'enable_color:is(on)',
			'operator'    => 'and',
		),
		array(
			'id'          => 'more_text_color',
			'label'       => __('Readmore Text Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'condition'   => 'enable_color:is(on)',
			'operator'    => 'and',
		),
		array(
			'id'          => 'more_bg_color',
			'label'       => __('Readmore Background Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'condition'   => 'enable_color:is(on)',
			'operator'    => 'and',
		),
		array(
			'id'          => 'more_hover_text_color',
			'label'       => __('Readmore Hover Text Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'condition'   => 'enable_color:is(on)',
			'operator'    => 'and',
		),
		array(
			'id'          => 'more_hover_bg_color',
			'label'       => __('Readmore Hover Background Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'colorpicker',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'condition'   => 'enable_color:is(on)',
			'operator'    => 'and',
		),
		array(
			'id'          => 'bg',
			'label'       => __('Heading Text Color', 'tally_taxdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'background',
			'section'     => '',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'choices'     => '',
			'condition'   => 'enable_color:is(on)',
			'operator'    => 'and',
		),
	)
);
$settings[] = array(
	'id'          => $the_prefix.'column',
	'label'       => __('Columns', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'column'),
	'type'        => 'text',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'margin',
	'label'       => __('Margin', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'margin'),
	'type'        => 'text',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);

$settings[] = array(
	'id'          => $the_prefix.'image_size',
	'label'       => __('Image Size', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'image_size'),
	'type'        => 'text',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'heading_color',
	'label'       => __('Heading Text Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'heading_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'text_color',
	'label'       => __('Text Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'text_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'border_color',
	'label'       => __('Border Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'border_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'more_text_color',
	'label'       => __('Readmore Text Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'more_text_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'more_bg_color',
	'label'       => __('Readmore Background Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'more_bg_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'more_hover_text_color',
	'label'       => __('Readmore Hover Text Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'more_hover_text_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);
$settings[] = array(
	'id'          => $the_prefix.'more_hover_bg_color',
	'label'       => __('Readmore Hover Background Color', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'more_hover_bg_color'),
	'type'        => 'colorpicker',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);

$settings[] = array(
	'id'          => $the_prefix.'bg',
	'label'       => __('Background', 'tally_taxdomain'),
	'desc'        => '',
	'std'         => tally_hp_option_std($the_prefix .'bg_color'),
	'type'        => 'background',
	'section'     => $the_section_id,
	'rows'        => '5',
	'post_type'   => '',
	'taxonomy'    => '',
	'class'       => '',
	'choices'     => '',
	'condition'   => $the_prefix.'enable:is(on),'.$section_prefix.'enable:is(on)',
	'operator'    => 'and',
);