<?php
$tally_config = array(
'slideshow_enable' => 'on',
'slideshow_slideshow_enable' => 'on',
'slideshow_slideshow_items' => array(
	array(
		'title' => 'title',
		'des' => 'Using this setting you can enable or disable this section of the home page. 
All option of the section will be show when you will select ON.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/ingredients-498199.jpg',
		'text_align' => 'left',
		'link' => '#',
		'button_text' => 'Hello',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'accent',
	),
	array(
		'title' => 'Using this setting you can enable',
		'des' => 'Using this setting you can enable or disable this section of the home page. 
All option of the section will be show when you will select ON.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/fashion-605508.jpg',
		'text_align' => 'left',
		'link' => '#',
		'button_text' => 'Button Text',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'accent',
	),
	array(
		'title' => '',
		'des' => '',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/girl-380621.jpg',
		'text_align' => 'left',
		'link' => '',
		'button_text' => '',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'accent',
	),
),
'slideshow_slideshow_image_size' => '1400x600',
'slideshow_slideshow_control_nav' => 'on',
'slideshow_slideshow_direction_nav' => 'on',
'three_column_text_enable' => 'on',
'three_column_text_col1_enable' => 'on',
'three_column_text_col1_column' => '4',
'three_column_text_col1_title' => 'First Column',
'three_column_text_col1_content' => '<p><iframe src="https://www.youtube.com/embed/dfGZ8NyGFS8?rel=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>',
'three_column_text_col1_align' => 'left',
'three_column_text_col1_buttons' => array(
	array(
		'title' => 'Read More',
		'link' => '#',
		'color' => 'dark',
		'target' => '_self',
		'class' => '',
	),
),
'three_column_text_col1_heading_color' => '',
'three_column_text_col1_text_color' => '',
'three_column_text_col1_border_color' => '',
'three_column_text_col2_enable' => 'on',
'three_column_text_col2_column' => '4',
'three_column_text_col2_title' => 'Second Column',
'three_column_text_col2_content' => '<p><img class="alignnone size-medium wp-image-49" src="http://localhost/boldway/wp-content/uploads/2015/03/woman-593141-300x200.jpg" alt="woman-593141" width="300" height="200" /></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>',
'three_column_text_col2_align' => 'left',
'three_column_text_col2_buttons' => array(
	array(
		'title' => 'Read More',
		'link' => '#',
		'color' => 'accent',
		'target' => '_self',
		'class' => '',
	),
),
'three_column_text_col2_heading_color' => '',
'three_column_text_col2_text_color' => '',
'three_column_text_col2_border_color' => '',
'three_column_text_col3_enable' => 'on',
'three_column_text_col3_column' => '4',
'three_column_text_col3_title' => 'Third Column',
'three_column_text_col3_content' => '<p><a href="http://localhost/boldway/wp-content/uploads/2015/03/woman-593141.jpg"><img class="alignnone size-medium wp-image-49" src="http://localhost/boldway/wp-content/uploads/2015/03/woman-593141-300x200.jpg" alt="woman-593141" width="300" height="200" /></a></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>',
'three_column_text_col3_align' => 'left',
'three_column_text_col3_buttons' => array(
	array(
		'title' => 'More',
		'link' => '#',
		'color' => 'dark',
		'target' => '_self',
		'class' => '',
	),
),
'three_column_text_col3_heading_color' => '',
'three_column_text_col3_text_color' => '',
'three_column_text_col3_border_color' => '',
'three_column_text_bg' => '',
'three_column_text_css_class' => '',
'three_column_text_css_id' => '',
'three_column_text_content_width' => '499',
'three_column_text_padding' => array(
	'top' => '60',
	'bottom' => '60',
),
'three_column_text_border_top' => '',
'three_column_text_border_bottom' => '',
'text1_enable' => 'on',
'text1_text1_enable' => 'on',
'text1_text1_title' => 'This is a Parallax Section',
'text1_text1_content' => '<p>Using this setting you can enable or disable this section of the home page. All option of the section will be show when you will select ON.Using this setting you can enable or disable this section of the home page.<br /> All option of the section will be show when you will select ON.</p>',
'text1_text1_align' => 'center',
'text1_text1_buttons' => array(
	array(
		'title' => 'Contact Us',
		'link' => '#',
		'color' => 'accent',
		'target' => '_self',
		'class' => '',
	),
	array(
		'title' => 'Email Us',
		'link' => '#',
		'color' => 'light',
		'target' => '_self',
		'class' => '',
	),
),
'text1_text1_heading_color' => '#ffffff',
'text1_text1_text_color' => '#ffffff',
'text1_text1_border_color' => '#ffffff',
'text1_bg' => array(
	'background-color' => '#6d6d6d',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/top-bg.jpg',
),
'text1_css_class' => '',
'text1_css_id' => '',
'text1_content_width' => '850',
'text1_padding' => array(
	'top' => '150',
	'bottom' => '150',
),
'text1_border_top' => '',
'text1_border_bottom' => '',
'section4_enable' => 'on',
'section4_content_enable' => 'on',
'section4_content_column' => '4',
'section4_content_title' => 'Column width select.',
'section4_content_content' => '<p><img class=" wp-image-50 size-medium aligncenter" src="http://lorempixel.com/400/200/fashion/" alt="blonde-629726" />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>
<p> </p>',
'section4_content_align' => 'left',
'section4_content_heading_color' => '',
'section4_content_text_color' => '',
'section4_content_border_color' => '',
'section4_tab_enable' => 'on',
'section4_tab_column' => '4',
'section4_tab_items' => array(
	array(
		'title' => 'Hello',
		'icon' => 'fa-bullhorn',
		'content' => '<p><img src="http://lorempixel.com/400/150/fashion/" alt="" /></p>
<h4>This is a Hello Tab</h4>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi. Curabitur elit lacus, cursus at nunc sit amet, rutrum molestie odio.</p>',
	),
	array(
		'title' => 'Ashik',
		'icon' => 'fa-lock',
		'content' => '<p><a href="http://localhost/boldway/wp-content/uploads/2015/03/startup-593302.jpg"><img class="alignright size-thumbnail wp-image-22" src="http://localhost/boldway/wp-content/uploads/2015/03/startup-593302-150x150.jpg" alt="startup-593302" width="150" height="150" /></a>Nam vel tincidunt diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent in tempus nisi. Sed congue lacinia turpis ut ullamcorper.</p>',
	),
),
'section4_tab_nav_color' => '#000000',
'section4_tab_nav_bg' => '#eaeaea',
'section4_tab_nav_border_color' => '#eaeaea',
'section4_tab_nav_active_color' => '#000000',
'section4_tab_nav_active_bg' => '#ffffff',
'section4_tab_box_text_color' => '#3d3d3d',
'section4_tab_box_bg_color' => '#ffffff',
'section4_tab_box_border_color' => '#eaeaea',
'section4_sidebar_enable' => 'on',
'section4_sidebar_column' => '4',
'section4_sidebar_heading_color' => '',
'section4_sidebar_text_color' => '',
'section4_sidebar_border_color' => '',
'section4_sidebar_bg' => '',
'section4_bg' => '',
'section4_css_class' => '',
'section4_css_id' => '',
'section4_content_width' => '499',
'section4_padding' => array(
	'top' => '60',
	'bottom' => '60',
),
'section4_border_top' => '',
'section4_border_bottom' => '',
'section5_enable' => 'on',
'section5_quoteSlider_enable' => 'on',
'section5_quoteSlider_items' => array(
	array(
		'title' => 'Jinny Wise',
		'position' => 'WEB DESIGN STUDENT',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/vintage-635244.jpg',
		'link' => '#',
	),
	array(
		'title' => 'John Doe',
		'position' => 'Web Design Business Student',
		'des' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/girl-380621.jpg',
		'link' => '',
	),
	array(
		'title' => 'James',
		'position' => 'WordPress Expert',
		'des' => 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/woman-593141.jpg',
		'link' => '#',
	),
),
'section5_quoteSlider_image_size' => '120x120',
'section5_quoteSlider_control_nav' => 'on',
'section5_quoteSlider_direction_nav' => 'on',
'section5_quoteSlider_text_color' => '#ffffff',
'section5_quoteSlider_border_color' => '#ffffff',
'section5_bg' => array(
	'background-color' => '#5e5e5e',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/top-bg.jpg',
),
'section5_css_class' => '',
'section5_css_id' => '',
'section5_content_width' => '1256',
'section5_padding' => array(
	'top' => '100',
	'bottom' => '100',
),
'section5_border_top' => '',
'section5_border_bottom' => '',
'section6_enable' => 'on',
'section6_people_enable' => 'on',
'section6_people_items' => array(
	array(
		'title' => 'Jay Poco',
		'position' => 'WordPress Developer',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/vintage-635244.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'Lorem ipsum',
		'position' => 'HTML Expert',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/blonde-629726.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'Varius Neque',
		'position' => 'Jquery Expert',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/woman-593141.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'Nisi Bibendum',
		'position' => 'HTML Expert',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/girl-380621.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
),
'section6_people_image_size' => '200x200',
'section6_people_columns' => '2',
'section6_people_column_margin' => '0.5',
'section6_people_heading_color' => '#000000',
'section6_people_text_color' => '#595959',
'section6_people_border_color' => '#e8e8e8',
'section6_people_bg_color' => '#ffffff',
'section6_header_enable' => 'on',
'section6_title' => 'Team Members',
'section6_description' => '<h4>Meet our beautiful team members.</h4>
<p> </p>',
'section6_align' => 'center',
'section6_header_text_color' => '',
'section6_header_heading_color' => '',
'section6_header_border_color' => '',
'section6_bg' => '',
'section6_css_class' => '',
'section6_css_id' => '',
'section6_content_width' => '499',
'section6_padding' => array(
	'top' => '60',
	'bottom' => '60',
),
'section6_border_top' => '',
'section6_border_bottom' => '',
'section7_enable' => 'on',
'section7_newsletter1_enable' => 'on',
'section7_newsletter1_html' => '<form action="">
<input type="text" placeholder="Email" />
<input type="text" placeholder="Email" />
<input type="submit" value="Subscribe" />
</form>',
'section7_newsletter1_des' => '<h4>Newsletter Signup</h4>
<p>Get Updates from us. Also we don\'t spam.</p>',
'section7_newsletter1_heading_color' => '#ffffff',
'section7_newsletter1_text_color' => '#ffffff',
'section7_newsletter1_border_color' => '#ffffff',
'section7_bg' => array(
	'background-color' => '#dd3333',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'section7_css_class' => '',
'section7_css_id' => '',
'section7_content_width' => '499',
'section7_padding' => array(
	'top' => '30',
	'bottom' => '30',
),
'section7_border_top' => '',
'section7_border_bottom' => '',
'section8_enable' => 'on',
'section8_infobox_enable' => 'on',
'section8_infobox_items' => array(
	array(
		'title' => 'Lorem ipsum',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas.',
		'icon' => 'fa-cab',
		'link' => '#',
		'class' => '',
	),
	array(
		'title' => 'Nunc vitae',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas.',
		'icon' => 'fa-cubes',
		'link' => '#',
		'class' => '',
	),
	array(
		'title' => 'Duis convallis',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas.',
		'icon' => 'fa-anchor',
		'link' => '#',
		'class' => '',
	),
	array(
		'title' => 'Nunc vehicula',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas.',
		'icon' => 'fa-bell-slash',
		'link' => '#',
		'class' => '',
	),
),
'section8_infobox_column' => '',
'section8_infobox_margin' => '',
'section8_infobox_icon_color' => '#ffffff',
'section8_infobox_icon_bg_color' => '#dd3333',
'section8_infobox_icon_border_color' => '#cecece',
'section8_infobox_icon_hover_color' => '#dd3333',
'section8_infobox_icon_hover_bg_color' => '#ffffff',
'section8_infobox_icon_hover_border_color' => '#dd3333',
'section8_infobox_heading_color' => '#000000',
'section8_infobox_text_color' => '#444444',
'section8_infobox_border_color' => '#d1d1d1',
'section8_infobox_bg_color' => '#ffffff',
'section8_header_enable' => 'on',
'section8_title' => 'Our Services',
'section8_description' => '<h4><strong>Using this setting you can enable or disable this section of the home page.</strong></h4>
<p> </p>',
'section8_align' => 'center',
'section8_header_text_color' => '',
'section8_header_heading_color' => '',
'section8_header_border_color' => '',
'section8_bg' => array(
	'background-color' => '#ededed',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'section8_css_class' => '',
'section8_css_id' => '',
'section8_content_width' => '499',
'section8_padding' => array(
	'top' => '60',
	'bottom' => '30',
),
'section8_border_top' => '',
'section8_border_bottom' => '',
'section9_enable' => 'on',
'section9_gallery1_enable' => 'on',
'section9_gallery1_gallery' => '50,49,48,29,40,41,42,22,61,63,64,65,66,67,68',
'section9_gallery1_image_size' => '400x400',
'section9_gallery1_column' => '5',
'section9_gallery1_margin' => '0',
'section12_enable' => 'on',
'section12_contactInfo_enable' => 'on',
'section12_contactInfo_column' => '12',
'section12_contactInfo_title' => 'Contact With Us',
'section12_contactInfo_des' => '',
'section12_contactInfo_align' => 'center',
'section12_contactInfo_email' => 'hello@tallythemes.com',
'section12_contactInfo_phone' => '123 456 7893',
'section12_contactInfo_address' => '1600 Pennsylvania Ave NW, Washington, DC 20500',
'section12_contactInfo_text_color' => '',
'section12_contactInfo_border_color' => '',
'section12_contactInfo_icon_color' => '#ffffff',
'section12_contactInfo_icon_bg' => '#dd3333',
'section12_contactInfo_icon_border_color' => '#dd3333',
'section12_contactform_enable' => 'on',
'section12_contactform_column' => '12',
'section12_contactform_title' => '',
'section12_contactform_des' => '',
'section12_contactform_email' => 'hello@tallythemes.com',
'section12_contactform_subject' => 'Email From Contact Form',
'section12_contactform_fields' => array(
	array(
		'title' => 'Name',
		'type' => 'text',
		'des' => '',
		'required' => 'on',
		'placeholder' => 'on',
		'class' => '',
		'width' => '2',
	),
	array(
		'title' => 'EmaiL',
		'type' => 'email',
		'des' => '',
		'required' => 'on',
		'placeholder' => 'on',
		'class' => '',
		'width' => '2',
	),
	array(
		'title' => 'Phone',
		'type' => 'text',
		'des' => '',
		'required' => 'off',
		'placeholder' => 'on',
		'class' => '',
		'width' => '2',
	),
	array(
		'title' => 'Subject',
		'type' => 'text',
		'des' => '',
		'required' => 'on',
		'placeholder' => 'on',
		'class' => '',
		'width' => '2',
	),
	array(
		'title' => 'Message',
		'type' => 'text',
		'des' => '',
		'required' => 'off',
		'placeholder' => 'on',
		'class' => '',
		'width' => '1',
	),
),
'section12_contactform_submit_text' => 'Send Message',
'section12_contactform_div_class' => '',
'section12_contactform_text_color' => '',
'section12_contactform_border_color' => '',
'section12_header_enable' => 'on',
'section12_title' => '',
'section12_description' => '',
'section12_align' => 'left',
'section12_header_text_color' => '',
'section12_header_heading_color' => '',
'section12_header_border_color' => '',
'section12_bg' => '',
'section12_css_class' => '',
'section12_css_id' => '',
'section12_content_width' => '499',
'section12_padding' => array(
	'top' => '80',
	'bottom' => '70',
),
'section12_border_top' => '',
'section12_border_bottom' => '',
'section10_enable' => 'on',
'section10_googlemap_enable' => 'on',
'section10_googlemap_title' => '',
'section10_googlemap_des' => '',
'section10_googlemap_address' => 'Dhaka, Bangladesh',
'section10_googlemap_infoWindow' => '<h4>This is Dhaka</h4>
<p><img src="http://placehold.it/200x100" alt="" /></p>
<p>Hello Dhaka is the capital of bangladesh. </p>',
'section10_googlemap_zoom' => '15',
'section10_googlemap_icon' => '',
'section10_googlemap_scrollwheel' => 'off',
'section10_googlemap_scaleControl' => 'off',
'section10_googlemap_navigationControl' => 'off',
'section10_googlemap_popup' => 'off',
'section10_googlemap_maptype' => 'HYBRID',
'section10_googlemap_width' => '100%',
'section10_googlemap_height' => '500px',
'section11_enable' => 'on',
'section11_contentbox_enable' => 'on',
'section11_contentbox_items' => array(
	array(
		'title' => 'Item One',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas. Using this setting you can enable or disable this section of the home page.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/photographer-428388.jpg',
		'link' => '#',
		'link_text' => 'More',
		'class' => '',
		'enable_color' => 'on',
		'heading_color' => '#000000',
		'text_color' => '#4f4f4f',
		'border_color' => '#dd3333',
		'more_text_color' => '#ffffff',
		'more_bg_color' => '#dd3333',
		'more_hover_text_color' => '#ffffff',
		'more_hover_bg_color' => '#1e73be',
		'bg' => '',
	),
	array(
		'title' => 'Lorem ipsum',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas. Using this setting you can enable or disable this section of the home page.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/ingredients-498199.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'class' => '',
		'enable_color' => 'off',
		'heading_color' => '',
		'text_color' => '',
		'border_color' => '',
		'more_text_color' => '',
		'more_bg_color' => '',
		'more_hover_text_color' => '',
		'more_hover_bg_color' => '',
		'bg' => '',
	),
	array(
		'title' => 'Ut eget varius',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas. Using this setting you can enable or disable this section of the home page.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/fashion-605508.jpg',
		'link' => '#',
		'link_text' => 'See Our Work',
		'class' => '',
		'enable_color' => 'off',
		'heading_color' => '',
		'text_color' => '',
		'border_color' => '',
		'more_text_color' => '',
		'more_bg_color' => '',
		'more_hover_text_color' => '',
		'more_hover_bg_color' => '',
		'bg' => '',
	),
	array(
		'title' => 'Mauris egestas',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas. Using this setting you can enable or disable this section of the home page.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/makeup-487063.jpg',
		'link' => '#',
		'link_text' => 'Our Blog',
		'class' => '',
		'enable_color' => 'off',
		'heading_color' => '',
		'text_color' => '',
		'border_color' => '',
		'more_text_color' => '',
		'more_bg_color' => '',
		'more_hover_text_color' => '',
		'more_hover_bg_color' => '',
		'bg' => '',
	),
	array(
		'title' => 'Consectetur Adipiscing',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas. Using this setting you can enable or disable this section of the home page.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/startup-593302.jpg',
		'link' => '#',
		'link_text' => 'Learn More',
		'class' => '',
		'enable_color' => 'off',
		'heading_color' => '',
		'text_color' => '',
		'border_color' => '',
		'more_text_color' => '',
		'more_bg_color' => '',
		'more_hover_text_color' => '',
		'more_hover_bg_color' => '',
		'bg' => '',
	),
	array(
		'title' => 'Mauris egestas',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas. Using this setting you can enable or disable this section of the home page.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/computer-416569.jpg',
		'link' => '#',
		'link_text' => 'Buy Now',
		'class' => '',
		'enable_color' => 'off',
		'heading_color' => '',
		'text_color' => '',
		'border_color' => '',
		'more_text_color' => '',
		'more_bg_color' => '',
		'more_hover_text_color' => '',
		'more_hover_bg_color' => '',
		'bg' => '',
	),
),
'section11_contentbox_column' => '3',
'section11_contentbox_margin' => '3',
'section11_contentbox_image_size' => '600x300',
'section11_contentbox_heading_color' => '#000000',
'section11_contentbox_text_color' => '#666666',
'section11_contentbox_border_color' => '#ffffff',
'section11_contentbox_more_text_color' => '#ffffff',
'section11_contentbox_more_bg_color' => '#dd3333',
'section11_contentbox_more_hover_text_color' => '#ffffff',
'section11_contentbox_more_hover_bg_color' => '#1e73be',
'section11_contentbox_bg' => '',
'section11_header_enable' => 'on',
'section11_title' => 'Content Boxes',
'section11_description' => '<h4>Lorem ipsum dolor sit amet.</h4>
<p> </p>',
'section11_align' => 'center',
'section11_header_text_color' => '',
'section11_header_heading_color' => '',
'section11_header_border_color' => '',
'section11_bg' => array(
	'background-color' => '#eaeaea',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'section11_css_class' => '',
'section11_css_id' => '',
'section11_content_width' => '499',
'section11_padding' => array(
	'top' => '60',
	'bottom' => '60',
),
'section11_border_top' => '',
'section11_border_bottom' => '',
);