<?php
$tally_config = array(
'slideshow_enable' => 'on',
'slideshow_slideshow_enable' => 'on',
'slideshow_slideshow_items' => array(
	array(
		'title' => 'Creative ideas for Tattoo',
		'des' => 'Ut telloribus eget elemetum vel curleif end elit. Aean auctoetnaliir pis nteerutru. Nulla fn nec ero ane ipsummis fauulet utricosere cubtsed leo pharetu nec augue. Aean auctoetnaliir pis nteerutru.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoos-743313_1280-1.jpg',
		'text_align' => 'center',
		'link' => '#',
		'button_text' => 'Read More',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'light',
	),
	array(
		'title' => 'Laser Tattoo Removal',
		'des' => 'Ut telloribus eget elemetum vel curleif end elit. Aean auctoetnaliir pis nteerutru. Nulla fn nec ero ane ipsummis fauulet utricosere cubtsed leo pharetu nec augue. Aean auctoetnaliir pis nteerutru.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoos-421711_1280-1.jpg',
		'text_align' => 'right',
		'link' => '#',
		'button_text' => 'Read More',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'light',
	),
	array(
		'title' => 'Realizing Your Dreams',
		'des' => 'Ut telloribus eget elemetum vel curleif end elit. Aean auctoetnaliir pis nteerutru. Nulla fn nec ero ane ipsummis fauulet utricosere cubtsed leo pharetu nec augue. Aean auctoetnaliir pis nteerutru.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/woman-314142_1280-1.jpg',
		'text_align' => 'left',
		'link' => '',
		'button_text' => '',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'light',
	),
),
'slideshow_slideshow_image_size' => '1400x600',
'slideshow_slideshow_control_nav' => 'on',
'slideshow_slideshow_direction_nav' => 'on',
'services_enable' => 'on',
'services_contentBox_enable' => 'on',
'services_contentBox_column' => '3',
'services_contentBox_items' => array(
	array(
		'title' => 'Tattoo',
		'des' => 'Mes cuml dia sed in lacus ut eniascet etor ingerto aliiqt es sitet amet eismod ictorut ligulate ameti dapibus ticdu nt mtsent lusto dolor ltisim comme. Mes cuml dia sed inertio lacus ut eniascet ingerto aliiqt sit amet eism odictor',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoo-702133_1280.jpg',
		'link' => '',
		'link_text' => '',
		'class' => '',
		'enable_color' => 'off',
		'heading_color' => '',
		'text_color' => '',
		'border_color' => '',
		'more_text_color' => '',
		'more_bg_color' => '',
		'more_hover_text_color' => '',
		'more_hover_bg_color' => '',
		'bg' => '',
	),
	array(
		'title' => 'Piercing',
		'des' => 'Mes cuml dia sed in lacus ut eniascet etor ingerto aliiqt es sitet amet eismod ictorut ligulate ameti dapibus ticdu nt mtsent lusto dolor ltisim comme. Mes cuml dia sed inertio lacus ut eniascet ingerto aliiqt sit amet eism odictor',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/body-piercing-371961_1280.jpg',
		'link' => '',
		'link_text' => '',
		'class' => '',
		'enable_color' => 'off',
		'heading_color' => '',
		'text_color' => '',
		'border_color' => '',
		'more_text_color' => '',
		'more_bg_color' => '',
		'more_hover_text_color' => '',
		'more_hover_bg_color' => '',
		'bg' => '',
	),
	array(
		'title' => 'Body art',
		'des' => 'Mes cuml dia sed in lacus ut eniascet etor ingerto aliiqt es sitet amet eismod ictorut ligulate ameti dapibus ticdu nt mtsent lusto dolor ltisim comme. Mes cuml dia sed inertio lacus ut eniascet ingerto aliiqt sit amet eism odictor',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/art-620890_1280.jpg',
		'link' => '',
		'link_text' => '',
		'class' => '',
		'enable_color' => 'off',
		'heading_color' => '',
		'text_color' => '',
		'border_color' => '',
		'more_text_color' => '',
		'more_bg_color' => '',
		'more_hover_text_color' => '',
		'more_hover_bg_color' => '',
		'bg' => '',
	),
),
'services_contentBox_margin' => '3',
'services_contentBox_image_size' => '400x150',
'services_contentBox_heading_color' => '',
'services_contentBox_text_color' => '',
'services_contentBox_border_color' => '',
'services_contentBox_more_text_color' => '',
'services_contentBox_more_bg_color' => '',
'services_contentBox_more_hover_text_color' => '',
'services_contentBox_more_hover_bg_color' => '',
'services_contentBox_bg' => array(
	'background-color' => '#424242',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'services_title' => '',
'services_description' => '',
'services_align' => 'left',
'services_header_text_color' => '',
'services_header_heading_color' => '',
'services_header_border_color' => '',
'services_bg' => '',
'services_css_class' => '',
'services_css_id' => 'services',
'services_content_width' => '499',
'services_padding' => array(
	'top' => '80',
	'bottom' => '60',
),
'services_border_top' => '',
'services_border_bottom' => '',
'our_work_enable' => 'on',
'our_work_imageGallery_enable' => 'on',
'our_work_imageGallery_gallery' => '11,10,9,8,12,13,14,15,16,17,18,19',
'our_work_imageGallery_image_size' => '400x360',
'our_work_imageGallery_column' => '4',
'our_work_imageGallery_margin' => '2',
'our_work_header_enable' => 'on',
'our_work_title' => 'Our Work',
'our_work_description' => '<h4>Checkout our gallery here.</h4>',
'our_work_align' => 'center',
'our_work_header_text_color' => '',
'our_work_header_heading_color' => '',
'our_work_header_border_color' => '',
'our_work_bg' => array(
	'background-color' => '#424242',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'our_work_css_class' => '',
'our_work_css_id' => '',
'our_work_content_width' => '499',
'our_work_padding' => array(
	'top' => '80',
	'bottom' => '60',
),
'our_work_border_top' => '',
'our_work_border_bottom' => '',
'parallax_enable' => 'on',
'parallax_content_enable' => 'on',
'parallax_content_title' => 'SO YOU WANT A TATTOO?',
'parallax_content_content' => '<h5>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</h5>',
'parallax_content_align' => 'center',
'parallax_content_buttons' => array(
	array(
		'title' => 'Contact With Us',
		'link' => '#',
		'color' => 'light',
		'target' => '_self',
		'class' => '',
	),
),
'parallax_content_heading_color' => '',
'parallax_content_text_color' => '',
'parallax_content_border_color' => '',
'parallax_bg' => array(
	'background-color' => '',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoos-743313_12802.jpg',
),
'parallax_css_class' => '',
'parallax_css_id' => '',
'parallax_content_width' => '900',
'parallax_padding' => array(
	'top' => '100',
	'bottom' => '100',
),
'parallax_border_top' => '',
'parallax_border_bottom' => '',
'artists_enable' => 'on',
'artists_people_enable' => 'on',
'artists_people_items' => array(
	array(
		'title' => 'Adam Carter',
		'position' => 'Tattoo Expert',
		'des' => 'Praesent vestibulum molestie lacus. Aenean nonuy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoos-421711_1280.jpg',
		'link' => '',
		'link_text' => '',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '',
		'instagram' => '',
	),
	array(
		'title' => 'Lisa Johnson',
		'position' => 'Body Art Expert',
		'des' => 'Praesent vestibulum molestie lacus. Aenean nonuy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/woman-598186_1280.jpg',
		'link' => '',
		'link_text' => '',
		'facebook' => '#',
		'twitter' => '#',

		'google' => '#',
		'linkedin' => '',
		'instagram' => '',
	),
	array(
		'title' => 'John Anderson',
		'position' => 'Piercing Expert ',
		'des' => 'Praesent vestibulum molestie lacus. Aenean nonuy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoo-728314_1280.jpg',
		'link' => '',
		'link_text' => '',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '',
		'instagram' => '',
	),
	array(
		'title' => 'Olivia Grosh',
		'position' => 'Tattoo expert',
		'des' => 'Praesent vestibulum molestie lacus. Aenean nonuy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/woman-314142_1280.jpg',
		'link' => '',
		'link_text' => '',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '',
		'instagram' => '',
	),
),
'artists_people_image_size' => '400x400',
'artists_people_columns' => '2',
'artists_people_column_margin' => '1',
'artists_people_heading_color' => '',
'artists_people_text_color' => '',
'artists_people_border_color' => '',
'artists_people_bg_color' => '',
'artists_header_enable' => 'on',
'artists_title' => 'Our Artists',
'artists_description' => '<h4>We have world class people</h4>',
'artists_align' => 'center',
'artists_header_text_color' => '',
'artists_header_heading_color' => '',
'artists_header_border_color' => '',
'artists_bg' => '',
'artists_css_class' => '',
'artists_css_id' => '',
'artists_content_width' => '499',
'artists_padding' => array(
	'top' => '80',
	'bottom' => '80',
),
'artists_border_top' => '',
'artists_border_bottom' => '',
'testimonials_enable' => 'on',
'testimonials_quoteSlider_enable' => 'on',
'testimonials_quoteSlider_items' => array(
	array(
		'title' => 'Lisa Johnson',
		'position' => 'Tattoo',
		'des' => 'Praesent vestibulum molestie lacus. Aenean nonuy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/woman-314142_1280.jpg',
		'link' => '',
	),
	array(
		'title' => 'Adam Carter',
		'position' => 'Body Art',
		'des' => 'Praesent vestibulum molestie lacus. Aenean nonuy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoos-421711_1280.jpg',
		'link' => '',
	),
	array(
		'title' => 'Olivia Grosh',
		'position' => 'Piercing',
		'des' => 'Praesent vestibulum molestie lacus. Aenean nonuy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes.',
		'image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/woman-598186_1280.jpg',
		'link' => '',
	),
),
'testimonials_quoteSlider_image_size' => '100x100',
'testimonials_quoteSlider_text_color' => '',
'testimonials_quoteSlider_border_color' => '#ffffff',
'testimonials_header_enable' => 'off',
'testimonials_title' => 'Customer Testimonials',
'testimonials_description' => '<p> </p>
<p> </p>',
'testimonials_align' => 'center',
'testimonials_header_text_color' => '',
'testimonials_header_heading_color' => '',
'testimonials_header_border_color' => '',
'testimonials_bg' => array(
	'background-color' => '',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center top',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoo-476096_1280-2.jpg',
),
'testimonials_css_class' => '',
'testimonials_css_id' => '',
'testimonials_content_width' => '499',
'testimonials_padding' => array(
	'top' => '100',
	'bottom' => '70',
),
'testimonials_border_top' => '',
'testimonials_border_bottom' => '',
'what_we_offer_enable' => 'on',
'what_we_offer_infoBox_enable' => 'on',
'what_we_offer_infoBox_items' => array(
	array(
		'title' => 'Gothic Tattoo',
		'des' => 'Cum sociis natoque penatibus et magnis dis parturient montes ascetur ridiculus mus.',
		'icon' => 'fa-paint-brush',
		'link' => '',
		'class' => '',
	),
	array(
		'title' => 'Facial Piercing',
		'des' => 'Cum sociis natoque penatibus et magnis dis parturient montes ascetur ridiculus mus.',
		'icon' => 'fa-thumb-tack',
		'link' => '',
		'class' => '',
	),
	array(
		'title' => 'Fantasy Tattoo',
		'des' => 'Cum sociis natoque penatibus et magnis dis parturient montes ascetur ridiculus mus.',
		'icon' => 'fa-pencil',
		'link' => '',
		'class' => '',
	),
	array(
		'title' => 'Japanese Tattoo',
		'des' => 'Cum sociis natoque penatibus et magnis dis parturient montes ascetur ridiculus mus.',
		'icon' => 'fa-paint-brush',
		'link' => '',
		'class' => '',
	),
),
'what_we_offer_infoBox_column' => '4',
'what_we_offer_infoBox_margin' => '2',
'what_we_offer_infoBox_icon_color' => '#ffffff',
'what_we_offer_infoBox_icon_bg_color' => '#ffc801',
'what_we_offer_infoBox_icon_border_color' => '#ffffff',
'what_we_offer_infoBox_icon_hover_color' => '#ffc801',
'what_we_offer_infoBox_icon_hover_bg_color' => '#ffffff',
'what_we_offer_infoBox_icon_hover_border_color' => '#ffc801',
'what_we_offer_infoBox_heading_color' => '',
'what_we_offer_infoBox_text_color' => '',
'what_we_offer_infoBox_border_color' => '',
'what_we_offer_infoBox_bg_color' => '#3f3f3f',
'what_we_offer_bg' => '',
'what_we_offer_css_class' => '',
'what_we_offer_css_id' => '',
'what_we_offer_content_width' => '499',
'what_we_offer_padding' => array(
	'top' => '80',
	'bottom' => '60',
),
'what_we_offer_border_top' => '',
'what_we_offer_border_bottom' => '',
'parallax2_enable' => 'on',
'parallax2_content_enable' => 'on',
'parallax2_content_column' => '4',
'parallax2_content_title' => 'Be Our Happy Customer',
'parallax2_content_content' => '<h5>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod</h5>
<h5>tincidunt ut laoreet dolore magna aliquam erat volutpat.</h5>',
'parallax2_content_align' => 'left',
'parallax2_content_buttons' => array(
	array(
		'title' => 'Order Online',
		'link' => '#',
		'color' => 'light',
		'target' => '_self',
		'class' => '',
	),
	array(
		'title' => 'Find More',
		'link' => '#',
		'color' => 'light',
		'target' => '_self',
		'class' => '',
	),
),
'parallax2_content_heading_color' => '',
'parallax2_content_text_color' => '',
'parallax2_content_border_color' => '',
'parallax2_bg' => array(
	'background-color' => '',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoo-349891_1280-2.jpg',
),
'parallax2_css_class' => '',
'parallax2_css_id' => '',
'parallax2_content_width' => '499',
'parallax2_padding' => array(
	'top' => '120',
	'bottom' => '120',
),
'parallax2_border_top' => '',
'parallax2_border_bottom' => '',
'contact_enable' => 'on',
'contact_googleMap_enable' => 'on',
'contact_googleMap_column' => '6',
'contact_googleMap_title' => '',
'contact_googleMap_des' => '',
'contact_googleMap_address' => '1600 Pennsylvania Ave NW, Washington, DC 20500, USA',
'contact_googleMap_infoWindow' => '<h2>The White House</h2>',
'contact_googleMap_zoom' => '15',
'contact_googleMap_icon' => '',
'contact_googleMap_maptype' => 'ROADMAP',
'contact_googleMap_width' => '',
'contact_googleMap_height' => '540px',
'contact_contactForm_enable' => 'on',
'contact_contactForm_column' => '4',
'contact_contactForm_title' => '',
'contact_contactForm_des' => '<h4>Contact With Us</h4>',
'contact_contactForm_email' => 'hello@tallythemes.com',
'contact_contactForm_subject' => 'Message from Contact page',
'contact_contactForm_fields' => array(
	array(
		'title' => 'Name',
		'type' => 'text',
		'des' => '',
		'required' => 'on',
		'placeholder' => 'on',
		'class' => '',
		'width' => '1',
	),
	array(
		'title' => 'Email',
		'type' => 'email',
		'des' => '',
		'required' => 'on',
		'placeholder' => 'on',
		'class' => '',
		'width' => '1',
	),
	array(
		'title' => 'Phone',
		'type' => 'text',
		'des' => '',
		'required' => 'off',
		'placeholder' => 'on',
		'class' => '',
		'width' => '1',
	),
	array(
		'title' => 'Message',
		'type' => 'textarea',
		'des' => '',
		'required' => 'on',
		'placeholder' => 'on',
		'class' => '',
		'width' => '1',
	),
),
'contact_contactForm_submit_text' => 'Send Message',
'contact_contactForm_div_class' => '',
'contact_contactForm_text_color' => '',
'contact_contactForm_border_color' => '',
'contact_contactInfo_enable' => 'on',
'contact_contactInfo_column' => '2',
'contact_contactInfo_title' => '',
'contact_contactInfo_des' => '',
'contact_contactInfo_align' => 'left',
'contact_contactInfo_email' => 'Hello@tallythemes.com',
'contact_contactInfo_phone' => '000 000 0000',
'contact_contactInfo_address' => ' 1600 Pennsylvania Ave NW',
'contact_contactInfo_text_color' => '',
'contact_contactInfo_border_color' => '',
'contact_contactInfo_icon_color' => '',
'contact_contactInfo_icon_bg' => '',
'contact_contactInfo_icon_border_color' => '',
'contact_bg' => array(
	'background-color' => '#515151',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'contact_css_class' => '',
'contact_css_id' => '',
'contact_content_width' => '499',
'contact_padding' => '',
'contact_border_top' => '',
'contact_border_bottom' => '',
);