<?php
$tally_config = array(
'slideshow_enable' => 'on',
'slideshow_slideshow_enable' => 'on',
'slideshow_slideshow_items' => array(
	array(
		'title' => 'title',
		'des' => 'Using this setting you can enable or disable this section of the home page. 
All option of the section will be show when you will select ON.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/ingredients-498199.jpg',
		'text_align' => 'left',
		'link' => '#',
		'button_text' => 'Hello',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'accent',
	),
	array(
		'title' => 'Using this setting you can enable',
		'des' => 'Using this setting you can enable or disable this section of the home page. 
All option of the section will be show when you will select ON.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/fashion-605508.jpg',
		'text_align' => 'left',
		'link' => '#',
		'button_text' => 'Button Text',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'accent',
	),
	array(
		'title' => '',
		'des' => '',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/girl-380621.jpg',
		'text_align' => 'left',
		'link' => '',
		'button_text' => '',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'accent',
	),
),
'slideshow_slideshow_image_size' => '1200x400',
'slideshow_slideshow_control_nav' => 'on',
'slideshow_slideshow_direction_nav' => 'on',
'three_column_text_enable' => 'on',
'three_column_text_col1_enable' => 'on',
'three_column_text_col1_column' => '4',
'three_column_text_col1_title' => 'First Column',
'three_column_text_col1_content' => '<p><iframe src="https://www.youtube.com/embed/dfGZ8NyGFS8?rel=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>',
'three_column_text_col1_align' => 'left',
'three_column_text_col1_buttons' => array(
	array(
		'title' => 'Read More',
		'link' => '#',
		'color' => 'dark',
		'target' => '_self',
		'class' => '',
	),
),
'three_column_text_col1_heading_color' => '',
'three_column_text_col1_text_color' => '',
'three_column_text_col1_border_color' => '',
'three_column_text_col2_enable' => 'on',
'three_column_text_col2_column' => '4',
'three_column_text_col2_title' => 'Second Column',
'three_column_text_col2_content' => '<p><img class="alignnone size-medium wp-image-49" src="http://localhost/boldway/wp-content/uploads/2015/03/woman-593141-300x200.jpg" alt="woman-593141" width="300" height="200" /></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>',
'three_column_text_col2_align' => 'left',
'three_column_text_col2_buttons' => array(
	array(
		'title' => 'Read More',
		'link' => '#',
		'color' => 'accent',
		'target' => '_self',
		'class' => '',
	),
),
'three_column_text_col2_heading_color' => '',
'three_column_text_col2_text_color' => '',
'three_column_text_col2_border_color' => '',
'three_column_text_col3_enable' => 'on',
'three_column_text_col3_column' => '4',
'three_column_text_col3_title' => 'Third Column',
'three_column_text_col3_content' => '<p><a href="http://localhost/boldway/wp-content/uploads/2015/03/woman-593141.jpg"><img class="alignnone size-medium wp-image-49" src="http://localhost/boldway/wp-content/uploads/2015/03/woman-593141-300x200.jpg" alt="woman-593141" width="300" height="200" /></a></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>',
'three_column_text_col3_align' => 'left',
'three_column_text_col3_buttons' => array(
	array(
		'title' => 'More',
		'link' => '#',
		'color' => 'dark',
		'target' => '_self',
		'class' => '',
	),
),
'three_column_text_col3_heading_color' => '',
'three_column_text_col3_text_color' => '',
'three_column_text_col3_border_color' => '',
'three_column_text_bg' => '',
'three_column_text_css_class' => '',
'three_column_text_css_id' => '',
'three_column_text_content_width' => '499',
'three_column_text_padding' => array(
	'top' => '60',
	'bottom' => '30',
),
'three_column_text_border_top' => '',
'three_column_text_border_bottom' => '',
'text1_enable' => 'on',
'text1_text1_enable' => 'on',
'text1_text1_title' => 'This is a Parallax Section',
'text1_text1_content' => '<p>Using this setting you can enable or disable this section of the home page. All option of the section will be show when you will select ON.Using this setting you can enable or disable this section of the home page.<br /> All option of the section will be show when you will select ON.</p>',
'text1_text1_align' => 'center',
'text1_text1_buttons' => array(
	array(
		'title' => 'Contact Us',
		'link' => '#',
		'color' => 'accent',
		'target' => '_self',
		'class' => '',
	),
	array(
		'title' => 'Email Us',
		'link' => '#',
		'color' => 'light',
		'target' => '_self',
		'class' => '',
	),
),
'text1_text1_heading_color' => '#ffffff',
'text1_text1_text_color' => '#ffffff',
'text1_text1_border_color' => '#ffffff',
'text1_bg' => array(
	'background-color' => '#6d6d6d',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/top-bg.jpg',
),
'text1_css_class' => '',
'text1_css_id' => '',
'text1_content_width' => '850',
'text1_padding' => array(
	'top' => '150',
	'bottom' => '150',
),
'text1_border_top' => '',
'text1_border_bottom' => '',
'section4_enable' => 'on',
'section4_content_enable' => 'on',
'section4_content_column' => '3',
'section4_content_title' => 'Column width select.',
'section4_content_content' => '<p><img class=" wp-image-50 size-medium aligncenter" src="http://localhost/boldway/wp-content/uploads/2015/03/blonde-629726-300x200.jpg" alt="blonde-629726" width="300" height="200" />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>
<p> </p>',
'section4_content_align' => 'left',
'section4_content_heading_color' => '',
'section4_content_text_color' => '',
'section4_content_border_color' => '',
'section4_tab_enable' => 'on',
'section4_tab_column' => '6',
'section4_tab_items' => array(
	array(
		'title' => 'Hello',
		'icon' => 'fa-bullhorn',
		'content' => '<p><img src="http://placehold.it/492x150" alt="" /></p>
<h4>This is a Hello Tab</h4>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi. Curabitur elit lacus, cursus at nunc sit amet, rutrum molestie odio.</p>',
	),
	array(
		'title' => 'Ashik',
		'icon' => 'fa-lock',
		'content' => '<p><a href="http://localhost/boldway/wp-content/uploads/2015/03/startup-593302.jpg"><img class="alignright size-thumbnail wp-image-22" src="http://localhost/boldway/wp-content/uploads/2015/03/startup-593302-150x150.jpg" alt="startup-593302" width="150" height="150" /></a>Nam vel tincidunt diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent in tempus nisi. Sed congue lacinia turpis ut ullamcorper.</p>',
	),
),
'section4_tab_nav_color' => '#000000',
'section4_tab_nav_bg' => '#eaeaea',
'section4_tab_nav_border_color' => '#eaeaea',
'section4_tab_nav_active_color' => '#000000',
'section4_tab_nav_active_bg' => '#ffffff',
'section4_tab_box_text_color' => '#3d3d3d',
'section4_tab_box_bg_color' => '#ffffff',
'section4_tab_box_border_color' => '#eaeaea',
'section4_sidebar_enable' => 'on',
'section4_sidebar_column' => '3',
'section4_sidebar_heading_color' => '',
'section4_sidebar_text_color' => '',
'section4_sidebar_border_color' => '',
'section4_sidebar_bg' => '',
'section4_bg' => '',
'section4_css_class' => '',
'section4_css_id' => '',
'section4_content_width' => '499',
'section4_padding' => array(
	'top' => '60',
),
'section4_border_top' => '',
'section4_border_bottom' => '',
'section5_enable' => 'on',
'section5_quoteSlider_enable' => 'on',
'section5_quoteSlider_items' => array(
	array(
		'title' => 'Jinny Wise',
		'position' => 'WEB DESIGN STUDENT',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/vintage-635244.jpg',
		'link' => '#',
	),
	array(
		'title' => 'John Doe',
		'position' => 'Web Design Business Student',
		'des' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/girl-380621.jpg',
		'link' => '',
	),
	array(
		'title' => 'James',
		'position' => 'WordPress Expert',
		'des' => 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/woman-593141.jpg',
		'link' => '#',
	),
),
'section5_quoteSlider_image_size' => '120x120',
'section5_quoteSlider_control_nav' => 'on',
'section5_quoteSlider_direction_nav' => 'on',
'section5_quoteSlider_text_color' => '#ffffff',
'section5_quoteSlider_border_color' => '#ffffff',
'section5_bg' => array(
	'background-color' => '#5e5e5e',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/top-bg.jpg',
),
'section5_css_class' => '',
'section5_css_id' => '',
'section5_content_width' => '1256',
'section5_padding' => array(
	'top' => '100',
	'bottom' => '100',
),
'section5_border_top' => '',
'section5_border_bottom' => '',
'section6_enable' => 'on',
'section6_people_enable' => 'on',
'section6_people_items' => array(
	array(
		'title' => 'Jay Poco',
		'position' => 'WordPress Developer',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/vintage-635244.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'Lorem ipsum',
		'position' => 'HTML Expert',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/blonde-629726.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'Varius Neque',
		'position' => 'Jquery Expert',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/woman-593141.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'Nisi Bibendum',
		'position' => 'HTML Expert',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/girl-380621.jpg',
		'link' => '#',
		'link_text' => 'Read More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
),
'section6_people_image_size' => '200x200',
'section6_people_columns' => '2',
'section6_people_column_margin' => '0.5',
'section6_people_heading_color' => '#000000',
'section6_people_text_color' => '#595959',
'section6_people_border_color' => '#e8e8e8',
'section6_people_bg_color' => '#ffffff',
'section6_header_enable' => 'on',
'section6_title' => 'Team Members',
'section6_description' => '<h4>Meet our beautiful team members.</h4>
<p> </p>',
'section6_align' => 'center',
'section6_header_text_color' => '',
'section6_header_heading_color' => '',
'section6_header_border_color' => '',
'section6_bg' => '',
'section6_css_class' => '',
'section6_css_id' => '',
'section6_content_width' => '499',
'section6_padding' => array(
	'top' => '60',
	'bottom' => '60',
),
'section6_border_top' => '',
'section6_border_bottom' => '',
);