<?php
$tally_config = array(
'site_logo' => '',
'site_logo_retina' => '',
'favicon' => '',
'enable_page_comment' => 'on',
'enable_post_comment' => 'on',
'header_info_text' => '',
'header_phone_number' => '1800-455-455',
'header_email_address' => 'hello@yourdomain.com',
'header_social_icons' => 'on',
'header_advertisment_code' => '',
'header_search_bar' => 'on',
'header_loginbox' => 'on',
'header_register_url' => '#',
'header_login_url' => '#',
'header_logout_url' => '#',
'header_profile_url' => '#',
'header_height' => '',
'header_menu_top_margin' => '',
'header_logo_top_margin' => '',
'header_text_color' => '#232323',
'header_link_color' => array(
	'link' => '#636363',
	'hover' => '#dd3333',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'header_border_color' => '#dbdbdb',
'header_bg' => '',
'header_topbar_text_color' => '#878787',
'header_topbar_link_color' => array(
	'link' => '#353535',
	'hover' => '#dd3333',
	'active' => '#eeee22',
	'visited' => '#dd9933',
	'focus' => '#8224e3',
),
'header_topbar_border_color' => '#e0e0e0',
'header_topbar_bg' => array(
	'background-color' => '#f2f2f2',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'nav_text_color' => '#636363',
'nav_border_color' => '',
'nav_bg_color' => '',
'nav_text_hover_color' => '#dd3333',
'nav_border_hover_color' => '',
'nav_bg_hover_color' => '',
'nav_sub_text_color' => '#848484',
'nav_sub_border_color' => '#e2e2e2',
'nav_sub_bg_color' => '#fcfcfc',
'nav_sub_text_hover_color' => '#dd3333',
'nav_sub_border_hover_color' => '#e2e2e2',
'nav_sub_bg_hover_color' => '#fff4f4',
'subheader_top_padding' => '',
'subheader_bottom_padding' => '',
'subheader_html' => '',
'subheader_title_color' => '#ffffff',
'subheader_subtitle_color' => '#ffffff',
'subheader_breadcrumbs_color' => '#ffffff',
'subheader_breadcrumbs_active_color' => '#fff7f7',
'subheader_breadcrumbs_divider_color' => '#fff7f7',
'subheader_border_color' => '#dbdbdb',
'subheader_bg' => array(
	'background-color' => '#dd3333',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/fashion-605508.jpg',
),
'primary_color' => '#dd3333',
'secondary_color' => '',
'color_headings' => '#333333',
'color_subheadings' => '#686868',
'color_text' => '#515151',
'color_meta' => '#898989',
'color_border' => '#d6d6d6',
'color_border2' => '#ededed',
'color_link' => array(
	'link' => '#dd3333',
	'hover' => '#1e73be',
	'active' => '#81d742',
	'visited' => '#dd6161',
	'focus' => '#dd0000',
),
'color_inner_bg' => '',
'color_content_bg' => '',
'site_background' => '',
'enable_google_fonts' => 'on',
'headings_google_font_link' => '',
'headings_google_font_family' => '',
'body_google_font_link' => '',
'body_google_font_family' => '',
'h1_font_size' => '',
'h2_font_size' => '',
'h3_font_size' => '',
'h4_font_size' => '',
'h5_font_size' => '',
'h6_font_size' => '',
'body_font_size' => '',
'enable_social_icons' => 'on',
'social_icons' => array(
	array(
		'title' => 'Dribbble',
		'link' => '#',
		'icon' => 'fa-dribbble',
	),
	array(
		'title' => 'Twitter',
		'link' => '#',
		'icon' => 'fa-twitter',
	),
	array(
		'title' => 'Facebok',
		'link' => '#',
		'icon' => 'fa-facebook',
	),
),
'footer_widget_layout' => '4',
'footer_copyright' => '',
'footer_w_heading_color' => '#ffffff',
'footer_w_text_color' => '#828282',
'footer_w_link_color' => array(
	'link' => '#a3a3a3',
	'hover' => '#ffffff',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'footer_w_border_color' => '#606060',
'footer_w_inner_border_color' => '#4c4c4c',
'footer_w_inner_bg_color' => '#4f4f4f',
'footer_w_bg' => array(
	'background-color' => '#3a3a3a',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'footer_c_text_color' => '#969696',
'footer_c_link_color' => array(
	'link' => '#b7b7b7',
	'hover' => '#ffffff',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'footer_c_border_color' => '#444343',
'footer_c_inner_border_color' => '#3f3f3f',
'footer_c_bg' => array(
	'background-color' => '#323232',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'blog_limit' => '1',
'blog_cat' => '1',
'blog_sidebar' => 'right',
'contact_description' => '',
'contact_email' => '',
'page_404_heading' => '',
'page_404_description' => '',
'page_404_search' => 'off',
'custom_css' => '',
'custom_js' => '',
'google_analytics' => '',
);