<?php
$tally_config = array(
'site_logo' => '',
'site_logo_retina' => '',
'favicon' => '',
'enable_page_comment' => 'on',
'enable_post_comment' => 'on',
'header_info_text' => 'ok\'s',
'header_phone_number' => '1800-455-455',
'header_email_address' => 'hello@yourdomain.com',
'header_social_icons' => 'on',
'header_advertisment_code' => '',
'header_search_bar' => 'on',
'header_loginbox' => 'on',
'header_register_url' => '#',
'header_login_url' => '#',
'header_logout_url' => '#',
'header_profile_url' => '#',
'header_height' => '',
'header_menu_top_margin' => '',
'header_logo_top_margin' => '',
'header_text_color' => '#232323',
'header_link_color' => array(
	'link' => '#636363',
	'hover' => '#dd3333',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'header_border_color' => '#dbdbdb',
'header_bg' => '',
'header_topbar_text_color' => '#555555',
'header_topbar_link_color' => array(
	'link' => '#353535',
	'hover' => '#dd3333',
	'active' => '#eeee22',
	'visited' => '#dd9933',
	'focus' => '#8224e3',
),
'header_topbar_border_color' => '#e7e7e7',
'header_topbar_bg' => array(
	'background-color' => '#ffffff',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'nav_text_color' => '#636363',
'nav_border_color' => '',
'nav_bg_color' => '',
'nav_text_hover_color' => '#dd3333',
'nav_border_hover_color' => '',
'nav_bg_hover_color' => '',
'nav_sub_text_color' => '#848484',
'nav_sub_border_color' => '#e2e2e2',
'nav_sub_bg_color' => '#fcfcfc',
'nav_sub_text_hover_color' => '#dd3333',
'nav_sub_border_hover_color' => '#e2e2e2',
'nav_sub_bg_hover_color' => '#fff4f4',
'subheader_top_padding' => '',
'subheader_bottom_padding' => '',
'subheader_html' => '',
'subheader_title_color' => '#ffffff',
'subheader_subtitle_color' => '#ffffff',
'subheader_breadcrumbs_color' => '#ffffff',
'subheader_breadcrumbs_active_color' => '#fff7f7',
'subheader_breadcrumbs_divider_color' => '#fff7f7',
'subheader_border_color' => '#dbdbdb',
'subheader_bg' => array(
	'background-color' => '#dd3333',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/fashion-605508.jpg',
),
'primary_color' => '#dd3333',
'secondary_color' => '',
'color_headings' => '#333333',
'color_subheadings' => '#686868',
'color_text' => '#515151',
'color_meta' => '#898989',
'color_border' => '#d6d6d6',
'color_border2' => '#ededed',
'color_link' => array(
	'link' => '#dd3333',
	'hover' => '#1e73be',
	'active' => '#81d742',
	'visited' => '#dd6161',
	'focus' => '#dd0000',
),
'color_inner_bg' => '',
'color_content_bg' => '',
'site_background' => '',
'enable_google_fonts' => 'on',
'headings_google_font_link' => '',
'headings_google_font_family' => '',
'body_google_font_link' => '',
'body_google_font_family' => '',
'h1_font_size' => '',
'h2_font_size' => '',
'h3_font_size' => '',
'h4_font_size' => '',
'h5_font_size' => '',
'h6_font_size' => '',
'body_font_size' => '',
'enable_social_icons' => 'on',
'social_icons' => array(
	array(
		'title' => 'Dribbble',
		'link' => '#',
		'icon' => 'fa-dribbble',
	),
	array(
		'title' => 'Twitter',
		'link' => '#',
		'icon' => 'fa-twitter',
	),
	array(
		'title' => 'Facebok',
		'link' => '#',
		'icon' => 'fa-facebook',
	),
),
'footer_widget_layout' => '4',
'footer_copyright' => '',
'footer_w_heading_color' => '#ffffff',
'footer_w_text_color' => '#828282',
'footer_w_link_color' => array(
	'link' => '#a3a3a3',
	'hover' => '#ffffff',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'footer_w_border_color' => '#606060',
'footer_w_inner_border_color' => '#4c4c4c',
'footer_w_inner_bg_color' => '#4f4f4f',
'footer_w_bg' => array(
	'background-color' => '#3a3a3a',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'footer_c_text_color' => '#969696',
'footer_c_link_color' => array(
	'link' => '#b7b7b7',
	'hover' => '#ffffff',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'footer_c_border_color' => '#444343',
'footer_c_inner_border_color' => '#3f3f3f',
'footer_c_bg' => array(
	'background-color' => '#323232',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'home_slideshow_enable' => 'on',
'home_slideshow_description' => '',
'home_slideshow_items' => array(
	array(
		'title' => 'Slidehow One',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/computer-416569.jpg',
		'text_align' => 'left',
		'link' => '#',
		'button_text' => 'Read More',
		'text_color' => '',
		'heading_color' => '',
		'button_color' => 'accent',
	),
	array(
		'title' => 'Lorem ipsum dolor',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/ingredients-498199.jpg',
		'text_align' => 'right',
		'link' => '#',
		'button_text' => 'Learn More',
		'text_color' => '#ffffff',
		'heading_color' => '#ffffff',
		'button_color' => 'light',
	),
	array(
		'title' => 'Nam libero tempore',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/imac-606765.jpg',
		'text_align' => 'center',
		'link' => '#',
		'button_text' => 'Contact Us Now!',
		'text_color' => '#494949',
		'heading_color' => '#000000',
		'button_color' => 'dark',
	),
),
'home_slideshow_image_size' => '1200x450',
'home_infoBox_enable' => 'on',
'home_infoBox_description' => '',
'home_infoBox_items' => array(
	array(
		'title' => 'Great Material',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.',
		'icon' => 'fa-star',
		'link' => '#',
		'class' => '',
	),
	array(
		'title' => 'High Quality',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.',
		'icon' => 'fa-cogs',
		'link' => '',
		'class' => '',
	),
	array(
		'title' => 'Learning is Fun',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.',
		'icon' => 'fa-heart',
		'link' => '#',
		'class' => '',
	),
	array(
		'title' => 'It\'s simple',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.',
		'icon' => 'fa-check',
		'link' => '#',
		'class' => '',
	),
),
'home_infoBox_columns' => '4',
'home_infoBox_margin' => '3',
'home_infoBox_padding' => array(
	'top' => '70',
	'bottom' => '40',
),
'home_infoBox_icon_color' => '#ffffff',
'home_infoBox_icon_hover_color' => '#dd3333',
'home_infoBox_icon_bg_color' => '#dd3333',
'home_infoBox_icon_bg_hover_color' => '#ffffff',
'home_infoBox_icon_border_color' => '#ddaaaa',
'home_infoBox_icon_border_hover_color' => '#dd3333',
'home_infoBox_text_color' => '#595959',
'home_infoBox_heading_color' => '#000000',
'home_infoBox_border_color' => '',
'home_infoBox_border_inner_color' => '#dd3333',
'home_infoBox__innerbg' => '#ffffff',
'home_infoBox_bg' => array(
	'background-color' => '#f4f4f4',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'scroll',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => '',
),
'home_textBlock_enable' => 'on',
'home_textBlock_content' => '<h1><strong>Love Our Themes</strong>.</h1>
<h4>If you want to buy any or this theme, please click on the buy now button below</h4>',
'home_textBlock_align' => 'center',
'home_textBlock_button_link' => '#',
'home_textBlock_button_text' => 'Buy Now',
'home_textBlock_button_text_color' => '#ffffff',
'home_textBlock_button_color' => '#dd3333',
'home_textBlock_button_hover_text_color' => '#ffffff',
'home_textBlock_button_hover_color' => '',
'home_textBlock_padding' => array(
	'top' => '120',
	'bottom' => '120',
),
'home_textBlock_text_color' => '#ffffff',
'home_textBlock_heading_color' => '#ffffff',
'home_textBlock_border_color' => '',
'home_textBlock_border_inner_color' => '',
'home_textBlock__innerbg' => '',
'home_textBlock_bg' => array(
	'background-color' => '#dddddd',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'scroll',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/ingredients-498199.jpg',
),
'home_blogGrid_enable' => 'on',
'home_blogGrid_description' => '<h2 style="text-align: center;">Our Blog</h2>
<h4 style="text-align: center;">Checkout our blog here.</h4>
<p> </p>',
'home_blogGrid_column' => '3',
'home_blogGrid_margin' => '4',
'home_blogGrid_limit' => '3',
'home_blogGrid_image_size' => '600x400',
'home_blogGrid_cat' => '',
'home_blogGrid_padding' => array(
	'top' => '50',
	'bottom' => '50',
	'unit' => 'px',
),
'home_blogGrid_text_color' => '#3f3f3f',
'home_blogGrid_heading_color' => '#000000',
'home_blogGrid_border_color' => '#e0e0e0',
'home_blogGrid_border_inner_color' => '#e0e0e0',
'home_blogGrid__innerbg' => '#ffffff',
'home_blogGrid_bg' => array(
	'background-color' => '#ffffff',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'scroll',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => '',
),
'home_textBlock2_enable' => 'on',
'home_textBlock2_content' => '<h1>Thsi is a Parallax Section</h1>',
'home_textBlock2_align' => 'center',
'home_textBlock2_button_link' => '',
'home_textBlock2_button_text' => '',
'home_textBlock2_button_text_color' => '',
'home_textBlock2_button_color' => '',
'home_textBlock2_button_hover_text_color' => '',
'home_textBlock2_button_hover_color' => '',
'home_textBlock2_padding' => array(
	'top' => '200',
	'bottom' => '180',
),
'home_textBlock2_text_color' => '',
'home_textBlock2_heading_color' => '#ffffff',
'home_textBlock2_border_color' => '',
'home_textBlock2_border_inner_color' => '',
'home_textBlock2__innerbg' => '',
'home_textBlock2_bg' => array(
	'background-color' => '',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => '',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/computer-416569.jpg',
),
'home_people_enable' => 'on',
'home_people_description' => '<h2 style="text-align: center;">Meet The Team</h2>
<p style="text-align: center;">Our professional and experienced lecturers will make your course wonderful.<br /> Our lecturers are practicing their field of expertise on daily basis.</p>
<p style="text-align: center;"> </p>',
'home_people_items' => array(
	array(
		'title' => 'Jay Poco',
		'subtitle' => 'WordPress Developer',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/vintage-635244.jpg',
		'link' => '#',
		'readmore_text' => 'More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'Lorem ipsum',
		'subtitle' => 'Owner of LLC',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/girl-380621.jpg',
		'link' => '#',
		'readmore_text' => 'More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'Ut eget',
		'subtitle' => 'Jquery Expert',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/woman-593141.jpg',
		'link' => '#',
		'readmore_text' => 'More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
	array(
		'title' => 'consectetur adipiscing',
		'subtitle' => 'HTML Expert',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/blonde-629726.jpg',
		'link' => '#',
		'readmore_text' => 'More',
		'facebook' => '#',
		'twitter' => '#',
		'google' => '#',
		'linkedin' => '#',
		'instagram' => '#',
	),
),
'home_people_columns' => '2',
'home_people_margin' => '0.5',
'home_people_image_size' => '200x200',
'home_people_padding' => array(
	'top' => '70',
	'bottom' => '70',
),
'home_people_text_color' => '#8c8c8c',
'home_people_heading_color' => '#000000',
'home_people_border_color' => '#d6d6d6',
'home_people_border_inner_color' => '#ededed',
'home_people__innerbg' => '#ffffff',
'home_people_bg' => array(
	'background-color' => '#f7f7f7',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'home_textBlock3_enable' => 'on',
'home_textBlock3_content' => '<h2 class="section-title">CREATIVE MULTIPURPOSE THEME</h2>
<p><span style="color: #3366ff;">EACH ELEMENT BEAUTIFULLY CRAFTED</span></p>
<p><a href="http://localhost/boldway/wp-content/uploads/2015/03/imac.jpg"><img class="alignnone size-full wp-image-54" src="http://localhost/boldway/wp-content/uploads/2015/03/imac.jpg" alt="imac" width="847" height="766" /></a></p>',
'home_textBlock3_align' => 'center',
'home_textBlock3_button_link' => '',
'home_textBlock3_button_text' => '',
'home_textBlock3_button_text_color' => '',
'home_textBlock3_button_color' => '',
'home_textBlock3_button_hover_text_color' => '',
'home_textBlock3_button_hover_color' => '',
'home_textBlock3_padding' => array(
	'top' => '80',
),
'home_textBlock3_text_color' => '',
'home_textBlock3_heading_color' => '',
'home_textBlock3_border_color' => '',
'home_textBlock3_border_inner_color' => '',
'home_textBlock3__innerbg' => '',
'home_textBlock3_bg' => '',
'home_quoteSlider_enable' => 'on',
'home_quoteSlider_description' => '<h2 style="text-align: center;">Our Customer</h2>
<p> </p>',
'home_quoteSlider_items' => array(
	array(
		'title' => 'Jinny Wise',
		'position' => 'WEB DESIGN STUDENT',
		'des' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/vintage-635244.jpg',
		'link' => '#',
	),
	array(
		'title' => 'John Doe',
		'position' => 'Web Design Business Student',
		'des' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/girl-380621.jpg',
		'link' => '',
	),
	array(
		'title' => 'James',
		'position' => 'WordPress Expert',
		'des' => 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.',
		'image' => 'http://localhost/boldway/wp-content/uploads/2015/03/woman-593141.jpg',
		'link' => '#',
	),
),
'home_quoteSlider_image_size' => '120x120',
'home_quoteSlider_padding' => array(
	'top' => '40',
	'bottom' => '80',
),
'home_quoteSlider_text_color' => '#000000',
'home_quoteSlider_heading_color' => '#000000',
'home_quoteSlider_border_color' => '#e8e8e8',
'home_quoteSlider_border_inner_color' => '#e8e8e8',
'home_quoteSlider__innerbg' => '#ffffff',
'home_quoteSlider_bg' => array(
	'background-color' => '#ffffff',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'home_textBlock4_enable' => 'on',
'home_textBlock4_content' => '<p><img class="alignnone size-full wp-image-55" src="http://localhost/boldway/wp-content/uploads/2015/03/logo.png" alt="logo" width="235" height="85" /></p>
<h1 class="text-center">MULTI-PURPOSE WORDPRESS THEME</h1>
<h4>CHOOSE THE DEMO YOU LIKE</h4>',
'home_textBlock4_align' => 'center',
'home_textBlock4_button_link' => '',
'home_textBlock4_button_text' => '',
'home_textBlock4_button_text_color' => '',
'home_textBlock4_button_color' => '',
'home_textBlock4_button_hover_text_color' => '',
'home_textBlock4_button_hover_color' => '',
'home_textBlock4_padding' => array(
	'top' => '200',
	'bottom' => '200',
),
'home_textBlock4_text_color' => '#ffffff',
'home_textBlock4_heading_color' => '#ffffff',
'home_textBlock4_border_color' => '',
'home_textBlock4_border_inner_color' => '',
'home_textBlock4__innerbg' => '',
'home_textBlock4_bg' => array(
	'background-color' => '',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/boldway/wp-content/uploads/2015/03/top-bg.jpg',
),
'home_videoText_enable' => 'on',
'home_videoText_description' => '',
'home_videoText_video' => '<iframe src="https://player.vimeo.com/video/121465494?title=0&byline=0&portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
'home_videoText_content' => '<h3>About TallyDesign</h3>
<div class="col-holder">
<div class="col col_6">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.</p>
<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. </p>
</div>
<div class="col col_6">
<p>Curabitur elit lacus, cursus at nunc sit amet, rutrum molestie odio. Duis convallis mattis mi quis eleifend.Nam vel tincidunt diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames. </p>
<p>Curabitur commodo libero augue, ac posuere augue volutpat vitae. Pellentesque ac nulla ipsum. Nunc vitae elit felis.</p>
</div>
</div>',
'home_videoText_padding' => array(
	'top' => '70',
	'bottom' => '1',
),
'home_videoText_text_color' => '',
'home_videoText_heading_color' => '',
'home_videoText_border_color' => '',
'home_videoText_border_inner_color' => '',
'home_videoText__innerbg' => '',
'home_videoText_bg' => array(
	'background-color' => '#f2f2f2',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'home_textBlock5_enable' => 'off',
'home_textBlock5_content' => '',
'home_textBlock5_align' => 'left',
'home_textBlock5_button_link' => '',
'home_textBlock5_button_text' => '',
'home_textBlock5_button_text_color' => '',
'home_textBlock5_button_color' => '',
'home_textBlock5_button_hover_text_color' => '',
'home_textBlock5_button_hover_color' => '',
'home_textBlock5_padding' => '',
'home_textBlock5_text_color' => '',
'home_textBlock5_heading_color' => '',
'home_textBlock5_border_color' => '',
'home_textBlock5_border_inner_color' => '',
'home_textBlock5__innerbg' => '',
'home_textBlock5_bg' => '',
'home_contact_enable' => 'on',
'home_contact_description' => '',
'home_contact_info' => '',
'home_contact_send_email' => '',
'home_contact_form_email' => '',
'home_contact_email_subject' => '',
'home_contact_from_des' => '',
'home_contact_padding' => '',
'home_contact_text_color' => '',
'home_contact_heading_color' => '',
'home_contact_border_color' => '',
'home_contact_border_inner_color' => '',
'home_contact__innerbg' => '',
'home_contact_bg' => '',
'blog_limit' => '1',
'blog_cat' => '1',
'blog_sidebar' => 'right',
'contact_description' => '',
'contact_email' => '',
'page_404_heading' => '',
'page_404_description' => '',
'page_404_search' => 'off',
'custom_css' => '',
'custom_js' => '',
'google_analytics' => '',
'adv_subheader_layout' => 'default',
);