<?php
$tally_config = array(
'site_logo' => '',
'site_logo_retina' => '',
'favicon' => '',
'enable_page_comment' => 'on',
'enable_post_comment' => 'on',
'header_info_text' => 'ok\'s',
'header_phone_number' => '1800-455-455',
'header_email_address' => 'hello@yourdomain.com',
'header_social_icons' => 'on',
'header_advertisment_code' => '',
'header_search_bar' => 'on',
'header_loginbox' => 'on',
'header_register_url' => '#',
'header_login_url' => '#',
'header_logout_url' => '#',
'header_profile_url' => '#',
'header_height' => '',
'header_menu_top_margin' => '',
'header_logo_top_margin' => '',
'header_text_color' => '#ffffff',
'header_link_color' => array(
	'link' => '#efefef',
	'hover' => '#dd3333',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'header_border_color' => '#515151',
'header_bg' => array(
	'background-color' => '#3a3a3a',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'header_topbar_text_color' => '#ffffff',
'header_topbar_link_color' => array(
	'link' => '#f2f2f2',
	'hover' => '#dd3333',
	'active' => '#eeee22',
	'visited' => '#dd9933',
	'focus' => '#8224e3',
),
'header_topbar_border_color' => '#515151',
'header_topbar_bg' => array(
	'background-color' => '#3a3a3a',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'nav_text_color' => '#ffffff',
'nav_border_color' => '',
'nav_bg_color' => '',
'nav_text_hover_color' => '#dd3333',
'nav_border_hover_color' => '',
'nav_bg_hover_color' => '',
'nav_sub_text_color' => '#848484',
'nav_sub_border_color' => '#e2e2e2',
'nav_sub_bg_color' => '#fcfcfc',
'nav_sub_text_hover_color' => '#dd3333',
'nav_sub_border_hover_color' => '#e2e2e2',
'nav_sub_bg_hover_color' => '#fff4f4',
'subheader_top_padding' => '50',
'subheader_bottom_padding' => '50',
'subheader_html' => '',
'subheader_title_color' => '#ffffff',
'subheader_subtitle_color' => '#f4f4f4',
'subheader_breadcrumbs_color' => '#ffffff',
'subheader_breadcrumbs_active_color' => '#ffffff',
'subheader_breadcrumbs_divider_color' => '#ffffff',
'subheader_border_color' => '#515151',
'subheader_bg' => array(
	'background-color' => '#444444',
	'background-repeat' => 'no-repeat',
	'background-attachment' => 'fixed',
	'background-position' => 'center center',
	'background-size' => 'cover',
	'background-image' => 'http://localhost/tallydesign/wp-content/uploads/2015/04/tattoo-476096_1280.jpg',
),
'primary_color' => '#dd3333',
'secondary_color' => '#dd9933',
'color_headings' => '#ffffff',
'color_subheadings' => '#f4f4f4',
'color_text' => '#f9f9f9',
'color_meta' => '#fcfcfc',
'color_border' => '#757575',
'color_border2' => '#666666',
'color_link' => array(
	'link' => '#dd3333',
	'hover' => '#1e73be',
	'active' => '#81d742',
	'visited' => '#dd6161',
	'focus' => '#dd0000',
),
'color_inner_bg' => '#666666',
'color_content_bg' => array(
	'background-color' => '#3a3a3a',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'site_background' => '',
'google_font' => array(
	array(
		'family' => 'raleway',
		array(
			'0' => 'regular',
			'1' => '500',
			'2' => '600',
			'3' => '700',
			'4' => '800',
			'5' => '900',
		),
		array(
			'0' => 'latin',
		),
	),
	array(
		'family' => 'roboto',
		array(
			'0' => '300',
			'1' => '300italic',
			'2' => 'regular',
			'3' => 'italic',
			'4' => '500',
			'5' => '500italic',
			'6' => '700',
			'7' => '700italic',
			'8' => '900',
			'9' => '900italic',
		),
	),
),
'font_body' => array(
	'font-color' => '',
	'font-family' => 'raleway',
	'font-size' => '14px',
	'font-style' => '',
	'font-variant' => '',
	'font-weight' => '',
	'letter-spacing' => '',
	'line-height' => '',
	'text-decoration' => '',
	'text-transform' => '',
),
'font_h1' => array(
	'font-color' => '',
	'font-family' => 'roboto',
	'font-size' => '',
	'font-style' => '',
	'font-variant' => '',
	'font-weight' => '',
	'letter-spacing' => '',
	'line-height' => '',
	'text-decoration' => '',
	'text-transform' => '',
),
'font_h2' => array(
	'font-color' => '',
	'font-family' => 'roboto',
	'font-size' => '',
	'font-style' => '',
	'font-variant' => '',
	'font-weight' => '900',
	'letter-spacing' => '',
	'line-height' => '',
	'text-decoration' => '',
	'text-transform' => '',
),
'font_h3' => array(
	'font-color' => '',
	'font-family' => 'roboto',
	'font-size' => '',
	'font-style' => '',
	'font-variant' => '',
	'font-weight' => '',
	'letter-spacing' => '',
	'line-height' => '',
	'text-decoration' => '',
	'text-transform' => '',
),
'font_h4' => array(
	'font-color' => '',
	'font-family' => 'roboto',
	'font-size' => '',
	'font-style' => '',
	'font-variant' => '',
	'font-weight' => '',
	'letter-spacing' => '',
	'line-height' => '',
	'text-decoration' => '',
	'text-transform' => '',
),
'font_h5' => array(
	'font-color' => '',
	'font-family' => 'roboto',
	'font-size' => '',
	'font-style' => '',
	'font-variant' => '',
	'font-weight' => '',
	'letter-spacing' => '',
	'line-height' => '',
	'text-decoration' => '',
	'text-transform' => '',
),
'font_h6' => array(
	'font-color' => '',
	'font-family' => 'roboto',
	'font-size' => '',
	'font-style' => '',
	'font-variant' => '',
	'font-weight' => '',
	'letter-spacing' => '',
	'line-height' => '',
	'text-decoration' => '',
	'text-transform' => '',
),
'enable_social_icons' => 'on',
'social_icons' => array(
	array(
		'title' => 'Dribbble',
		'link' => '#',
		'icon' => 'fa-dribbble',
	),
	array(
		'title' => 'Twitter',
		'link' => '#',
		'icon' => 'fa-twitter',
	),
	array(
		'title' => 'Facebok',
		'link' => '#',
		'icon' => 'fa-facebook',
	),
),
'footer_widget_layout' => '4',
'footer_copyright' => '',
'footer_w_heading_color' => '#ffffff',
'footer_w_text_color' => '#828282',
'footer_w_link_color' => array(
	'link' => '#a3a3a3',
	'hover' => '#ffffff',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'footer_w_border_color' => '#606060',
'footer_w_inner_border_color' => '#4c4c4c',
'footer_w_inner_bg_color' => '#4f4f4f',
'footer_w_bg' => array(
	'background-color' => '#3a3a3a',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'footer_c_text_color' => '#969696',
'footer_c_link_color' => array(
	'link' => '#b7b7b7',
	'hover' => '#ffffff',
	'active' => '',
	'visited' => '',
	'focus' => '',
),
'footer_c_border_color' => '#444343',
'footer_c_inner_border_color' => '#3f3f3f',
'footer_c_bg' => array(
	'background-color' => '#323232',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'blog_limit' => '1',
'blog_cat' => '1',
'contact_description' => '',
'contact_email' => '',
'page_404_heading' => '',
'page_404_description' => '',
'page_404_search' => 'off',
'custom_css' => '',
'custom_js' => '',
'google_analytics' => '',
'adv_subheader_layout' => 'default',
);